export const CERTIFICATES = [
  {
    id: "gmp",
    name: "GMP",
    descriptionKey: "certificates.gmp",
    image: "/certificates/gmp.svg",
    color: "#5eb53a",
  },
  {
    id: "iso",
    name: "ISO",
    descriptionKey: "certificates.iso",
    image: "/certificates/iso.svg",
    color: "#4a90d9",
  },
  {
    id: "halal",
    name: "HALAL",
    descriptionKey: "certificates.halal",
    image: "/certificates/halal.svg",
    color: "#c4a035",
  },
  {
    id: "mesti",
    name: "MESTI",
    descriptionKey: "certificates.mesti",
    image: "/certificates/mesti.svg",
    color: "#d44a2a",
  },
  {
    id: "fda",
    name: "FDA",
    descriptionKey: "certificates.fda",
    image: "/certificates/fda.svg",
    color: "#2a7aaa",
  },
  {
    id: "natural",
    name: "100% NATURAL",
    descriptionKey: "certificates.natural",
    image: "/certificates/natural.svg",
    color: "#6ab04a",
  },
  {
    id: "eac",
    name: "EAC",
    descriptionKey: "certificates.eac",
    image: "/certificates/eac.svg",
    color: "#3a8aaa",
  },
  {
    id: "vegan",
    name: "VEGAN",
    descriptionKey: "certificates.vegan",
    image: "/certificates/vegan.svg",
    color: "#7aab3a",
  },
] as const;
